/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Klasa00;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Tunwashe Daniel
 */
public class Klasa extends javax.swing.JFrame {
    
    Connection con;
    Statement stm;
    ResultSet rs;
    int cuRow;
    
    
    public void Konet(){
        
        try{
            
        String host = "jdbc:derby://localhost:1527/STUD";
        String uName = "Daniel";
        String uPass = "12345";
        
        
        // WE WILL THEN USE CONNECTION TO CONNECT AND PICK THE CONNECTION THAT WILL CONTAIN THREE VARIABLE AS SPECIFIED IN THE 
        con = DriverManager.getConnection(host, uName, uPass);
        
        // THIS CREATE STATEMENT ALLOWS US TO SLECT MODE
        stm = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        //ERITE ANY SQL STATEMENT
        String sql = "SELECT * FROM STUD";
        rs = stm.executeQuery(sql);
        rs.next();
        
        int mat1 = rs.getInt("MAT");
        String sur = rs.getString("SURNAME");
        String dept1 = rs.getString("DEPT");
        float gpa = rs.getFloat("GPA");
        
        //NOW WE WANT TO TRANSFER THE VALUES TO OUR FORM BUT THE INTEGERS AND NON STRINGS TYPE MUST FIRST BE CONVERTED TO STRINGS
        String mat2 = Integer.toString(mat1);
        String gpa2 = Float.toString(gpa);
        
        // NOW WE CAN ADD THEM TO THE TEXT BOXES CONSIDERING THE VARIABLE NAMES
        txtMat.setText(mat2);
        txtSur.setText(sur);
        txtDept.setText(dept1);
        txtGpa.setText(gpa2);
            
        }catch(SQLException err){
            JOptionPane.showMessageDialog(Klasa.this, err.getMessage());
        }
        
    }
    /**
     * Creates new form Klasa
     */
    public Klasa() {
        initComponents();
        Konet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMat = new javax.swing.JTextField();
        txtSur = new javax.swing.JTextField();
        txtDept = new javax.swing.JTextField();
        txtGpa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnAny = new javax.swing.JButton();
        txtAny = new javax.swing.JTextField();
        lblHint = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnNewRec = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSaveRec = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM");
        jLabel1.setToolTipText("");

        txtMat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatActionPerformed(evt);
            }
        });

        txtSur.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtDept.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtGpa.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("matric_No");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("surname");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("dept");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("gpa");

        btnNext.setBackground(new java.awt.Color(0, 0, 204));
        btnNext.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("next_rec");
        btnNext.setFocusTraversalPolicyProvider(true);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrev.setBackground(new java.awt.Color(0, 0, 204));
        btnPrev.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(255, 255, 255));
        btnPrev.setText("previous_rec");
        btnPrev.setFocusTraversalPolicyProvider(true);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnFirst.setBackground(new java.awt.Color(0, 0, 204));
        btnFirst.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnFirst.setForeground(new java.awt.Color(255, 255, 255));
        btnFirst.setText("first_rec");
        btnFirst.setFocusTraversalPolicyProvider(true);
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnLast.setBackground(new java.awt.Color(0, 0, 204));
        btnLast.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnLast.setForeground(new java.awt.Color(255, 255, 255));
        btnLast.setText("last_rec");
        btnLast.setFocusTraversalPolicyProvider(true);
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnAny.setBackground(new java.awt.Color(0, 0, 204));
        btnAny.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnAny.setForeground(new java.awt.Color(255, 255, 255));
        btnAny.setText("any_rec");
        btnAny.setFocusTraversalPolicyProvider(true);
        btnAny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnyActionPerformed(evt);
            }
        });

        txtAny.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblHint.setText("ENTER ANY INDEX TO GET THE CONTENT OF THE INDEX");

        btnCancel.setBackground(new java.awt.Color(0, 0, 204));
        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("cancelRec");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnNewRec.setBackground(new java.awt.Color(0, 0, 204));
        btnNewRec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNewRec.setForeground(new java.awt.Color(255, 255, 255));
        btnNewRec.setText("newRec");
        btnNewRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRecActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 0, 204));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("updateRec");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSaveRec.setBackground(new java.awt.Color(0, 0, 204));
        btnSaveRec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSaveRec.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveRec.setText("saveRec");
        btnSaveRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRecActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 0, 204));
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("deleteRec");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtSur, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(txtDept, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGpa, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMat, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAny)
                            .addComponent(lblHint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnNewRec, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSaveRec, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDept, txtGpa, txtMat, txtSur});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnPrev)
                    .addComponent(btnFirst)
                    .addComponent(btnLast))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHint, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAny, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSaveRec, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNewRec, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAny)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        
        try{
            
            if(rs.next()){
                
                int mat1 = rs.getInt("MAT");
                String sur = rs.getString("SURNAME");
                String dept1 = rs.getString("DEPT");
                float gpa1 = rs.getFloat("GPA");
                
                
                String mat2 = Integer.toString(mat1);
                String gpa2 = Float.toString(gpa1);
                
                
                txtMat.setText(mat2);
                txtSur.setText(sur);
                txtDept.setText(dept1);
                txtGpa.setText(gpa2);
                
                
            }else{
                
                rs.previous();
                JOptionPane.showMessageDialog(Klasa.this, "You have gotten to the end of the record......");
            }
            
        }catch (SQLException err){
            JOptionPane.showMessageDialog(Klasa.this, err.getMessage());
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        
        try{
            
            if(rs.previous()){
                
                int mat1 = rs.getInt("MAT");
                String sur = rs.getString("SURNAME");
                String dept1 = rs.getString("DEPT");
                float gpa1 = rs.getFloat("GPA");
                
                
                String mat2 = Integer.toString(mat1);
                String gpa2 = Float.toString(gpa1);
                
                
                txtMat.setText(mat2);
                txtSur.setText(sur);
                txtDept.setText(dept1);
                txtGpa.setText(gpa2);
                
                
            }else{
                
                rs.next();
                JOptionPane.showMessageDialog(Klasa.this, "You have gotten to the first record......");
            }
            
        }catch (SQLException err){
            JOptionPane.showMessageDialog(Klasa.this, err.getMessage());
        }
        
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        
        try{
            rs.first();
            if(rs.first()){
                
                int mat1 = rs.getInt("MAT");
                String sur = rs.getString("SURNAME");
                String dept1 = rs.getString("DEPT");
                float gpa1 = rs.getFloat("GPA");
                
                
                String mat2 = Integer.toString(mat1);
                String gpa2 = Float.toString(gpa1);
                
                
                txtMat.setText(mat2);
                txtSur.setText(sur);
                txtDept.setText(dept1);
                txtGpa.setText(gpa2);
                
            }
        
        
        }catch (SQLException err){
                
               JOptionPane.showMessageDialog(Klasa.this, err.getMessage());
                
        }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        
        try{
            rs.last();
            if(rs.last()){
                
                int mat1 = rs.getInt("MAT");
                String sur = rs.getString("SURNAME");
                String dept1 = rs.getString("DEPT");
                float gpa1 = rs.getFloat("GPA");
                
                
                String mat2 = Integer.toString(mat1);
                String gpa2 = Float.toString(gpa1);
                
                
                txtMat.setText(mat2);
                txtSur.setText(sur);
                txtDept.setText(dept1);
                txtGpa.setText(gpa2);
                
            }
        
        
        }catch (SQLException err){
                
               JOptionPane.showMessageDialog(Klasa.this, err.getMessage());
                
        }
        
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnAnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnyActionPerformed
        
        try {
            String s1 = txtAny.getText();
            int n1 = Integer.parseInt(s1);
            
            //we can use rs absolute to go to any record
                rs.absolute(n1);
                int mat1 = rs.getInt("MAT");
                String sur = rs.getString("SURNAME");
                String dept1 = rs.getString("DEPT");
                float gpa1 = rs.getFloat("GPA");
                
                
                String mat2 = Integer.toString(mat1);
                String gpa2 = Float.toString(gpa1);
                
                
                txtMat.setText(mat2);
                txtSur.setText(sur);
                txtDept.setText(dept1);
                txtGpa.setText(gpa2);
            
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(Klasa.this, err.getMessage());
        }
        
       
        
        
       
       
    }//GEN-LAST:event_btnAnyActionPerformed

    private void btnNewRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRecActionPerformed
        try{
        
        cuRow = rs.getRow();
        txtMat.setText("");
        txtSur.setText("");
        txtDept.setText("");
        txtGpa.setText("");
        
        btnNext.setEnabled(false);
        btnPrev.setEnabled(false);
        btnFirst.setEnabled(false);
        btnLast.setEnabled(false);
        btnAny.setEnabled(false);
        btnNewRec.setEnabled(false);
        btnSaveRec.setEnabled(true);
        btnCancel.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        
        }catch(SQLException err){
            
            JOptionPane.showMessageDialog(Klasa.this, err.getMessage());
            
        }
    }//GEN-LAST:event_btnNewRecActionPerformed

    private void btnSaveRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRecActionPerformed
        try{
            
            String mat1 = txtMat.getText();
            String sur1 = txtSur.getText();
            String dept1= txtDept.getText();
            String gpa1 = txtGpa.getText();
            
            int mat2 = Integer.parseInt(mat1);
            float gpa2 = Float.parseFloat(gpa1);
            
            //TO INSERT INTO THE DATABASE
            rs.moveToInsertRow();
            rs.updateInt("Mat", mat2);
            rs.updateString("SURNAME", sur1);
            rs.updateString("DEPT", dept1);
            rs.updateFloat("GPA", gpa2);
            rs.insertRow();
            rs.close();
            stm.close();
            
            
            
        stm = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        //ERITE ANY SQL STATEMENT
        String sql = "SELECT * FROM STUD";
        rs = stm.executeQuery(sql);
        rs.next();
        
        int mat3 = rs.getInt("MAT");
        String sur3 = rs.getString("SURNAME");
        String dept3 = rs.getString("DEPT");
        float gpa3 = rs.getFloat("GPA");
        
        //NOW WE WANT TO TRANSFER THE VALUES TO OUR FORM BUT THE INTEGERS AND NON STRINGS TYPE MUST FIRST BE CONVERTED TO STRINGS
        String mat4 = Integer.toString(mat3);
        String gpa4 = Float.toString(gpa3);
        
        // NOW WE CAN ADD THEM TO THE TEXT BOXES CONSIDERING THE VARIABLE NAMES
        txtMat.setText(mat4);
        txtSur.setText(sur3);
        txtDept.setText(dept3);
        txtGpa.setText(gpa4);
        
        
        txtMat.setText("");
        txtSur.setText("");
        txtDept.setText("");
        txtGpa.setText("");
        
        btnNext.setEnabled(true);
        btnPrev.setEnabled(true);
        btnFirst.setEnabled(true);
        btnLast.setEnabled(true);
        btnAny.setEnabled(true);
        btnNewRec.setEnabled(true);
        btnSaveRec.setEnabled(false);
        btnCancel.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
            
            
        }catch(SQLException err){
            
            JOptionPane.showMessageDialog(Klasa.this, err.getMessage());
        }
    }//GEN-LAST:event_btnSaveRecActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        
        try{
            
            rs.absolute(cuRow);
            txtMat.setText(Integer.toString(rs.getInt("MAT")));
            txtSur.setText(rs.getString("SURNAME"));
            txtDept.setText(rs.getString("DEPT"));
            txtMat.setText(Float.toString(rs.getFloat("GPA")));
            
            
        btnNext.setEnabled(true);
        btnPrev.setEnabled(true);
        btnFirst.setEnabled(true);
        btnLast.setEnabled(true);
        btnAny.setEnabled(true);
        btnNewRec.setEnabled(true);
        btnSaveRec.setEnabled(false);
        btnCancel.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        
        
        txtMat.setText("");
        txtSur.setText("");
        txtDept.setText("");
        txtGpa.setText("");
            
        }catch(SQLException err){
            
            JOptionPane.showMessageDialog(Klasa.this, err.getMessage());
        }
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
          try{
              
            String mat1 = txtMat.getText();
            String sur1 = txtSur.getText();
            String dept1= txtDept.getText();
            String gpa1 = txtGpa.getText();
            
            int mat2 = Integer.parseInt(mat1);
            float gpa2 = Float.parseFloat(gpa1);
            
            //TO UPDATE DATA TO THE DATABASE
            rs.updateInt("Mat", mat2);
            rs.updateString("SURNAME", sur1);
            rs.updateString("DEPT", dept1);
            rs.updateFloat("GPA", gpa2);
            
            rs.updateRow();
            
            JOptionPane.showMessageDialog(Klasa.this, "Record updated");
              
          }catch(SQLException err){
              
              JOptionPane.showMessageDialog(Klasa.this, err.getMessage());
          }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       try{
       
           rs.deleteRow();
           stm.close();
           rs.close();
           
           
        stm = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        //ERITE ANY SQL STATEMENT
        String sql = "SELECT * FROM STUD";
        rs = stm.executeQuery(sql);
        rs.next();
        
        int mat1 = rs.getInt("MAT");
        String sur = rs.getString("SURNAME");
        String dept1 = rs.getString("DEPT");
        float gpa = rs.getFloat("GPA");
        
        //NOW WE WANT TO TRANSFER THE VALUES TO OUR FORM BUT THE INTEGERS AND NON STRINGS TYPE MUST FIRST BE CONVERTED TO STRINGS
        String mat2 = Integer.toString(mat1);
        String gpa2 = Float.toString(gpa);
        
        // NOW WE CAN ADD THEM TO THE TEXT BOXES CONSIDERING THE VARIABLE NAMES
        txtMat.setText(mat2);
        txtSur.setText(sur);
        txtDept.setText(dept1);
        txtGpa.setText(gpa2);
       
       }catch(SQLException err){
           JOptionPane.showMessageDialog(Klasa.this, err.getMessage());
           
       }
           
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Klasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Klasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Klasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Klasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Klasa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAny;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNewRec;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSaveRec;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblHint;
    private javax.swing.JTextField txtAny;
    private javax.swing.JTextField txtDept;
    private javax.swing.JTextField txtGpa;
    private javax.swing.JTextField txtMat;
    private javax.swing.JTextField txtSur;
    // End of variables declaration//GEN-END:variables
}
